# Generated by Django 6.0.5 on 2026-05-31 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('date', models.DateField(verbose_name='Datum')),
                ('location', models.CharField(max_length=200, verbose_name='Ort')),
                ('description', models.TextField(verbose_name='Beschreibung')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name / Künstler:innenname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Telefonnummer optional')),
                ('art_form', models.CharField(max_length=200, verbose_name='Kunstform')),
                ('contribution_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Titel des Beitrags optional')),
                ('description', models.TextField(verbose_name='Kurze Beschreibung des Beitrags')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='Dauer in Minuten')),
                ('technical_needs', models.TextField(blank=True, default='', verbose_name='Technische Anforderungen')),
                ('portfolio_link', models.URLField(blank=True, default='', verbose_name='Link zu Portfolio / Instagram / Soundcloud optional')),
                ('consent_privacy', models.BooleanField(default=False, verbose_name='Ich stimme der Speicherung meiner Angaben zur Bearbeitung der Anmeldung zu.')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('accepted', 'Angenommen'), ('waitlist', 'Warteliste'), ('rejected', 'Abgelehnt')], default='new', max_length=20, verbose_name='Status')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Interne Notizen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingegangen am')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Gewünschter Termin')),
            ],
        ),
    ]
