# Generated by Django 6.0.5 on 2026-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='instagram_contact',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram-Kontakt'),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='portfolio_link',
            field=models.URLField(blank=True, default='', verbose_name='Link zu Portfolio / Website / Soundcloud optional'),
        ),
    ]
