# Generated by Django 6.0.5 on 2026-09-18 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_artistapplication_instagram_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Bild')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('is_published', models.BooleanField(default=True, verbose_name='Veröffentlicht')),
            ],
        ),
    ]
