# Generated by Django 5.0.9 on 2026-09-21 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_artistapplication_id_alter_event_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="gallery/videos/", verbose_name="Video"
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="gallery/images/", verbose_name="Bild"
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Titel"
            ),
        ),
        migrations.CreateModel(
            name="GalleryAlbum",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Beschreibung"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Datum")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Veröffentlicht"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                        verbose_name="Zugehöriger Termin",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="events.galleryalbum",
                verbose_name="Album",
            ),
        ),
    ]
